#!/bin/zsh
#== @conf

function source-all
{
    [ -f $HOME/etc/alias.zsh ] && source $HOME/etc/alias.zsh
    [ -f $HOME/etc/funcs.zsh ] && source $HOME/etc/funcs.zsh
    [ -f $HOME/etc/zshrc ] && source $HOME/etc/zshrc
    [ -f $HOME/bin/colors ] && source $HOME/bin/colors
    source-funcs
}

function source
{
    _FILE=$1
    case $_FILE in
        all) source-all;;
        alias) [ -f $HOME/etc/alias.zsh ] && source $HOME/etc/alias.zsh;;
        funcs) [ -f $HOME/etc/funcs.zsh ] && source $HOME/etc/funcs.zsh;;
        zshrc) [ -f $HOME/etc/zshrc ] && source $HOME/etc/zshrc;;
        zshenv) [ -f $HOME/etc/zshenv ] && source $HOME/etc/zshenv;;
        *) [ -f "$_FILE" ] && source $_FILE;;
    esac
}
