#!/bin/zsh
#== Personal help system
source $ZSHDIR/funcs.zsh

function myaliases #== Lists all system aliases in a nice, formatted manner. Used in @help
{
	echo ""
	gawk 'BEGIN { printf("\33[1;7;32m%-15s\33[34m%-80s\n\33[0m"," Alias"," Description") }'
	(cat $ZSHDIR/alias.zsh | grep "=\"" | sort | gawk --field-separator="=\"" '
		{
			if((FNR % 2) == 0)
				printf("'${bblk}'%-21s%-80s'${rst}'\n",$1,$2)
			else
				printf("%-21s%-80s\n",$1,$2)}' | sed -e "s:alias::" -e "s:\"::g")
}


function myfunctions #== Lists all system functions in a nice, formatted manner. Used in @help
{
	echo ""
	gawk 'BEGIN { printf("\33[1;7;32m%-20s\33[34m%-77s\33[0m"," Function"," Description") }'
	cat $ZSHDIR/funcs.zsh | gawk --field-separator=" #== " '/^function/{ sub(/function /,""); printf(" \033[32m%-22s\033[36m%-77s\n\033[0m",$1,$2)}' | sort | sed -e 's/()//'
}
    
function myscripts #== Lists all scripts in a nice, formatted manner. Used in @help
{
	echo ""
	gawk 'BEGIN { printf("\33[1;7;32m%-15s\33[34m%-77s\n\33[0m"," Script"," Description") }'
	(cd $HOME/bin && egrep '^#== ' * | gawk -F : '
		{
			if ((FNR % 2) == 0)
				printf("'${bblk}' %-15s%-80s'${rst}'\n",$1,$2)
			else
				printf(" %-15s%-80s\n",$1,$2)
		}' | sed -e "s/#== //")
}


function mykeys #== Lists all dwm keybindings in a nice, formatted manner. Used in @help
{
	gawk '
	BEGIN {
		printf("\n\33[1;7;32m%-21s\33[34m%-52s\n\33[0m"," Key"," Binding"," Description")
		FS="[#:]"
	}
	/\/\/#/ {
		if ((FNR % 2) == 0)
			printf("'${bblk}' %-21s%-51s'${rst}'\n",$2,$3)
		else
			printf(" %-21s%-50s\n",$2,$3)
	}
	END {
		printf("\n")
	}' $HOME/code/dwm/config.h
}

function filesystem
{
	echo ""
	gawk 'BEGIN { printf("\33[1;7;32m%-15s\33[34m%-50s\n\33[0m"," Directory"," Description") }'
	(cat $HOME/doc/txt/fhs | gawk -F , '{printf(" \033[32m%-16s\033[36m%-50s\n\033[0m",$1,$2)}')
}

case $1 in
	aliases)    myaliases                ;;
    alias)      myaliases                ;;
	functions)  myfunctions              ;;
    funcs)      myfunctions              ;;
	scripts)    myscripts                ;;
	keys)       mykeys                   ;;
	fhs)	    filesystem               ;;
	filesystem) filesystem		         ;;
	colors)     ansi && hexcol && coltable ;;
    cols)       ansi && hexcol && coltable ;;
	system)     archey                   ;;
    sys)        archey                   ;;
	*)          echo -e "${bld}${red}*${rst}You did not enter valid input.\n${ylw}Usage${rst}:\n\t@help <${blu}topic${rst}>\n\nWhere <${blu}topic${rst}> is one of:\n\taliases\n\tfunctions\n\tscripts\n\tkeys\n\tfilesystem\n\tcolors\n\tsystem" ;;
esac
