#!/bin/zsh
#== Adds the specified alias to the aliases file
ALIAS_F=$ZSHDIR/alias.zsh

if [ -z "$1" ]; then
	echo -e "[${red}error${rst}]No alias name specified"
	return 0
else
	if [ -z "$2" ]; then
		echo -e "[${red}error${rst}]No alias body specified"
		return 0
	else
		if [ -f $ALIAS_F ]; then
            echo alias $1="\"$2\"" >> $ALIAS_F
            echo -e "[${grn}success${rst}]Add alias to aliases file"
            source $ALIAS_F
			echo -e "[${grn}success${rst}]Source modified aliases file"
		else
			echo -e "[${red}error${rst}]Could not find alias file, please check configuration."
		fi
	fi
fi
