#!/bin/zsh
#== Backs up home directory, to be ran weekly

ARC_DIR=$(date +/storage/archive/home_w%W)

tar -cf $ARC_DIR.tar -v $HOME \
	--exclude=$HOME/audio/music \
	--exclude=$HOME/video \
	--exclude=$HOME/.bash_history \
	--exclude=$HOME/.cache \
	--exclude=$HOME/.config \
	--exclude=$HOME/.dbus \
	--exclude=$HOMES/.dmenu_cache \
	--exclude=$HOME/.esd_auth \
	--exclude=$HOME/.gimp-2.8 \
	--exclude=$HOME/.gksu.lock \
	--exclude=$HOME/.gnome \
	--exclude=$HOME/.gtk-bookmarks \
	--exclude=$HOME/.java \
	--exclude=$HOME/.local \
	--exclude=$HOME/.minecraft/assets \
	--exclude=$HOME/.minecraft/libraries \
	--exclude=$HOME/.minecraft/logs \
	--exclude=$HOME/.minecraft/versions \
	--exclude=$HOME/.minecraft/launcher.jar \
	--exclude=$HOME/.minecraft/launcher.pack.lzma \
	--exclude=$HOME/.minecraft/launcher_profiles.json \
	--exclude=$HOME/.minecraft/options.txt \
	--exclude=$HOME/.lyrics \
	--exclude=$HOME/.pki \
	--exclude=$HOME/.surf \
	--exclude=$HOME/.thumbnails \
	--exclude=$HOME/.viminfo \
	--exclude=$HOME/.volume \
	--exclude=$HOME/.Xauthority \
	--exclude=$HOME/.zcompdump \
	--exclude=$HOME/.zdirs \
	--exclude=$HOME/.zsh_history
gzip $ARC_DIR.tar