#!/usr/bin/env bash
#
# pbrisbin 2012
#
###
cache="$HOME/.dynamic-ip"
touch "$cache"

read -r old < "$cache"
read -r new < <(curl -s http://ipecho.net/plain)

[[ "$old" == "$new" ]] && exit 0

{
  cat > $HOME/tmp/ip.tmp << EOF
Your dynamic IP address seems to have changed.

  <$old> changed to
  <$new>

Please update accordingly at:

  https://account.dyn.com/dns/dyn-standard-dns/pbrisbin.com

EOF

}

zenity --text-info --filename=$HOME/tmp/ip.tmp --title="Your external IP Address has changed"
rm $HOME/tmp/ip.tmp
echo $new > "$cache"
