#!/bin/zsh
#== Contains ansi graphics escape sequences
# Formatting
rst="$(tput sgr0)"  # Reset
bold="$(tput bold)" # Bold
fant="$(tput dim)"  # Faint
ital="$(tput smul)" # Start Underline
blnk="$(tput rmul)" # End Underline
fbnk="$(tput smso)" # Standout Mode
revv="$(tput rev)"  # Reverse video
conc="$(tput rmso)" # Exit Standout Mode
# Foreground
blk="$(tput setaf 0)" # Black
red="$(tput setaf 1)" # Red
grn="$(tput setaf 2)" # Green
ylw="$(tput setaf 3)" # Yellow
blu="$(tput setaf 4)" # Blue
mag="$(tput setaf 5)" # Magenta
cyn="$(tput setaf 6)" # Cyan
wht="$(tput setaf 7)" # White
# Background
bblk="$(tput setab 0)" # Black
bred="$(tput setab 1)" # Red
bgrn="$(tput setab 2)" # Green
bylw="$(tput setab 3)" # Yellow
bblu="$(tput setab 4)" # Blue
bmag="$(tput setab 5)" # Magenta
bcyn="$(tput setab 6)" # Cyan
bwht="$(tput setab 7)" # White
# Script Type
subs="\e[48m" # Subscript
sups="\e[49m" # Superscript
# Other
eeos="$(tput ed)"    # Erase to end of screen
eeol="$(tput el)"    # Erase to end of line
ebol="$(tput el1)"   # Erase to beginning of line
urow="$(tput cuu 1)" # Move up a row
drow="$(tput cud 1)" # Move down a row
rcol="$(tput cuf 1)" # Move right a column
lcol="$(tput cub 1)" # Move left a column
spos="$(tput sc)"    # Save position
rpos="$(tput rc)"    # Restore position
lins="$(tput lines)" # Number of lines in terminal
cols="$(tput cols)"  # Number of columns in the terminal

info=${bld}${wht}*${rst} # Information
pass=${bld}${blu}*${rst} # Pass
warn=${bld}${ylw}*${rst} # Warning
fail=${bld}${red}*${rst} # Error
ques=${bld}${blu}?${rst} # Question

#Sets TTY colors
if [ "$TERM" = "linux" ]; then
    echo -en "\e]P0073642" #black
    echo -en "\e]P8002b36" #darkgrey
    echo -en "\e]P1dc322f" #darkred
    echo -en "\e]P9cb4b16" #red
    echo -en "\e]P2859900" #darkgreen
    echo -en "\e]PA586e75" #green
    echo -en "\e]P3b58900" #brown
    echo -en "\e]PB657b83" #yellow
    echo -en "\e]P4268bd2" #darkblue
    echo -en "\e]PC839496" #blue
    echo -en "\e]P5d33682" #darkmagenta
    echo -en "\e]PD6c71c4" #magenta
    echo -en "\e]P62aa198" #darkcyan
    echo -en "\e]PE93a1a1" #cyan
    echo -en "\e]P7eee8d5" #lightgrey
    echo -en "\e]PFfdf6e3" #white
    clear #for background artifacting
fi
