#!/bin/zsh
#== Shows system colors with hex values

xdef="$HOME/etc/xresources"

colors=( $( sed -re '/^!/d; /^$/d; /^#/d; s/(\.color)([0-9]):/\10\2:/g;' $xdef | grep 'color[01][0-9]:' | sort | sed  's/^.*: *//g' ) )

echo -e "\e[1;37m 
      BLK         RED         GRN         YLW         BLU         PNK         CYN         WHT   
───────────────────────────────────────────────────────────────────────────────────────────────────\e[0m"
for i in {0..7}; do echo -en "\e[$((30+$i))m ██ ${colors[i+1]} \e[0m"; done
echo
for i in {8..15}; do echo -en "\e[1;$((22+$i))m ██ ${colors[i+1]} \e[0m"; done
echo -e "\n"
