#!/bin/zsh
#== Downloads specified file(s), displaying progress in a dzen bar

SECS=5

(
    wget --progress=dot "$@" 2>&1;
    echo "Download(s) finished..";
    sleep $SECS;
) | dzen2 -bg "#222222" -fg "#336699" -x '710' -y '0' -w '500' -h '14' -fn '-*-bitocra-*-*-*-*-*-*-*-*-*-*-*-*' -e 'onstart=uncollapse;button3=exec:pkill -15 wget,exit' &
