#!/bin/zsh
#== OSD of Volume, with integrated control

#Customize this stuff
SECS="1.0"            # sleep $SECS
BG="#151515"        # background colour of window
FG="#B2B2B2"        # foreground colour of text/icon
BAR_FG="#385E6B"    # foreground colour of volume bar
BAR_BG="#B2B2B2"    # background colour of volume bar
#XPOS="835"          # horizontal positioning - left monitor
XPOS="835"         # horizontal positioning - right monitor
YPOS="525"          # vertical positioning
HEIGHT="30"         # window height
WIDTH="250"         # window width
BAR_WIDTH="180"     # width of volume bar
ICON=$HOME/images/icons/xbm8x8/spkr_04.xbm
FONT="-*-bitocra-*-*-*-*-*-*-*-*-*-*-*-*"
ICON_VOL=$HOME/images/icons/vol-100.xbm
ICON_VOL_MUTE=$HOME/images/icons/vol-mute.xbm
ICON_COL=$BAR_FG
ICON=$ICON_VOL
VOL_ARG=$2

#Probably do not customize
PIPE="/tmp/dvolpipe"

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: dvol [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -h, --help     - display this"
  exit 
}   
    
#Argument Parsing
case "$1" in 
  '-i'|'--increase')
    [ -z "$VOL_ARG" ] && err "No argument specified for increase."
    #[ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    pamixer --increase $VOL_ARG
    ;;
  '-d'|'--decrease')
    [ -z "$VOL_ARG" ] && err "No argument specified for decrease."
    #[ -n "$(tr -d [0-9] <<<$2)" ] && err "The argument needs to be an integer."
    pamixer --decrease $VOL_ARG
    ;;
  '-t'|'--toggle')
    pamixer --toggle-mute
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac

#Actual volume changing (readability low)
#AMIXOUT="$(amixer set "$IF" "$AMIXARG" | tail -n 1)"
#MUTE="$(cut -d '[' -f 4 <<<"$AMIXOUT")"
#VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"
#AMIXOUT="$(pamixer --set-volume $VOL_ARG)"
VOL="$(pamixer --get-volume | sed 's|%||')"
[ $(pamixer --get-mute) = "true" ] && ICON=$ICON_VOL_MUTE || ICON=$ICON_VOL

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
if [ ! -p "$PIPE" ]; then
  [ -e "$PIPE" ] && rm "$PIPE"
  if mkfifo "$PIPE" ; then
    (dzen2 -xs 1 -tw "$WIDTH" -h "$HEIGHT" -x "$XPOS" -y "$YPOS" -fn "$FONT" -bg "$BG" -fg "$FG" < "$PIPE"
    rm -f "$PIPE") &
  fi
fi

#Feed the pipe!
(echo "$VOL" | gdbar -l "^p(-8)^fg(${ICON_COL})^i(${ICON})^fg()^p(8)${VOL}% " -s o -h 14 -fg "$BAR_FG" -bg "$BAR_BG" -w "$BAR_WIDTH"; sleep "$SECS") > "$PIPE"
