#!/bin/bash
#== LibreOffice Menu
choice_by_dmenu() {
  DMENU='dmenu -p LibreOffice: -fn -*-bitocra13-*-*-*-*-*-*-*-*-*-*-*-* -l 10'

  choice=$(echo -e "0: Start Center\n1: New Document\n2: New Spreadsheet\n3: New Drawing\n4: New Presentation\n5: New Database\n6: New Equation\n7: New HTML Document" | $DMENU | cut -d ':' -f 1)
}

[[ -z "$DISPLAY" ]] && exit 1

choice_by_dmenu

[[ -z "$choice" ]] && exit 1

# execute the choice in background
case "$choice" in
  0) libreoffice --nologo           & ;;
  1) libreoffice --nologo --writer  & ;;
  2) libreoffice --nologo --calc    & ;;
  3) libreoffice --nologo --draw    & ;;
  4) libreoffice --nologo --impress & ;;
  5) libreoffice --nologo --base    & ;;
  6) libreoffice --nologo --math    & ;;
  7) libreoffice --nologo --web     & ;;
esac