#!/bin/zsh
#== Displays number of unread emails

if [ -r "$HOME/.dbus/Xdbus" ]; then
  . "$HOME/.dbus/Xdbus"
fi

count=$(wget --secure-protocol=TLSv1 --timeout=3 -t 1 -q -O - https://tyler.j.cw:979488Tjcw@mail.google.com/mail/feed/atom --no-check-certificate | grep 'fullcount' | sed -e 's/.*<fullcount>//;s/<\/fullcount>.*//') 2>/dev/null
notify-send "GMail" "You have ${count} unread emails"