#!/bin/zsh
#== Script to control MPD

case $1 in
	"next") mpc next
		$HOME/bin/mpd-notify;;
	"prev") mpc prev
		$HOME/bin/mpd-notify;;
	"play") mpc play
		$HOME/bin/mpd-notify;;
	"pause") mpc pause
		 $HOME/bin/mpd-notify;;
	"stop") mpc stop
		$HOME/bin/mpd-notify;;
	"toggle") mpc toggle
		  $HOME/bin/mpd-notify;;
	*) echo "You must give a command."
esac
