#!/bin/zsh
#== Displays system info and distro logo
# Script by SuNjACk
# Only for SuNjACk (muahahah! :D)
# Version: 0.2
# GPL License (do what do you what)

# --////////////////////////--
# --// Identify The Infos //--
# --////////////////////////--

# The GTK settings
gtkrc="$HOME/.gtkrc-2.0"
GtkTheme=$( grep "gtk-theme-name" "$gtkrc" | cut -d\" -f2 )
GtkIcon=$( grep "gtk-icon-theme-name" "$gtkrc" | cut -d\" -f2 )
GtkFont=$( grep "gtk-font-name" "$gtkrc" | cut -d\" -f2 )

# The Wallpaper set with nitrogen
nitroconf="$HOME/.config/nitrogen/bg-saved.cfg"
Wallpaper="$( cat $HOME/dotfiles/feh/fehbg | gawk '{ print $3 }' | sed -e "s/'//" -e "s/'//" -e 's!$HOME/pic/wallpapers/!!' )"

# Settings from ~/.Xdefaults
xdef="~/.Xdefaults"
TermFont="$(grep 'URxvt\*font' ~/.Xdefaults | cut -d\: -f2- | sed -re 's/xft://g; s/:size=(.*):.*/ \1/g; s/^ *//g')"

# Time and date
time=$( date "+%H.%M")
date=$( date "+%a %d %b" )

# OS
OS=$(cat /etc/issue | sed 's/\\.//g')

# WM version
WmVer=$( xmonad --version )

# --//////////////////////////////--
# --// Color for the higllights //--
# --//////////////////////////////--

cat-highlights-color () {
#    col=$( echo $1 | sed 's/-c//g' )
    col=${1#-c}
    case $col in
        0)  export H='\e[30m';;
        1)  export H='\e[31m';;
        2)  export H='\e[32m';;
        3)  export H='\e[33m';;
        4)  export H='\e[34m';;
        5)  export H='\e[35m';;
        6)  export H='\e[36m';;
        7)  export H='\e[37m';;
        8)  export H='\e[1;30m';;
        9)  export H='\e[1;31m';;
        10) export H='\e[1;32m';;
        11) export H='\e[1;33m';;
        12) export H='\e[1;34m';;
        13) export H='\e[1;35m';;
        14) export H='\e[1;36m';;
        15) export H='\e[1;37m';;
    esac
}

# --////////////////////////--
# --// Color for the logo //--
# --////////////////////////--

cat-logo-color () {
#    col=$( echo $1 | sed 's/-C//g' )
    col=${1#-C} 
    case $col in
        0)  export L='\e[30m';;
        1)  export L='\e[31m';;
        2)  export L='\e[32m';;
        3)  export L='\e[33m';;
        4)  export L='\e[34m';;
        5)  export L='\e[35m';;
        6)  export L='\e[36m';;
        7)  export L='\e[37m';;
        8)  export L='\e[1;30m';;
        9)  export L='\e[1;31m';;
        10) export L='\e[1;32m';;
        11) export L='\e[1;33m';;
        12) export L='\e[1;34m';;
        13) export L='\e[1;35m';;
        14) export L='\e[1;36m';;
        15) export L='\e[1;37m';;
    esac
}

# --//////////////////////////////--
# --// Different Distros' Logos //--
# --//////////////////////////////--

# null color
NC='\e[0m'

# --// Debian Logo //--
logo-debian () {
    test "$L"  || L='\e[;31m'
    test "$H"  || H='\e[1;34m'
    
    echo -e "
$L          _,edm88888on.$NC
$L       ,d888888888888888P.$NC
$L     ,g88P\"\"       \"\"\"Y88.\".$NC\t$H $time$NC - $date$NC
$L    ,88P'              \`888.$NC\t ${USER} \@ wolterBox $NC
$L   ,88P       ,ggs.     \`88b:$NC
$L   d88'     ,8P\"'   .    888$NC\t GTK Theme »$H $GtkTheme$NC
$L  \`88P      d8'     ,    88P$NC\t GTK Icons »$H $GtkIcon$NC
$L  \`88:      88.   -    ,d88'$NC\t GTK Font  »$H $GtkFont$NC
$L  \`88;      Y8b._   _,d8P'  $NC\t Term Font »$H $TermFont$NC
$L   Y88.    \`.\`\"Y8888P\"'$NC  \t Wallpaper »$H $Wallpaper$NC
$L   \`88b      \"-.__$NC
$L    \`Y88b$NC                   \t OS »$H $OS$NC
$L     \`Y88.$NC                  \t WM »$H $NC $WmVer
$L       \`88b.$NC
$L         \`Y88b.$NC
$L           \`\"Y8b._$NC
$L               \`\"\"\"\"$NC
"
    }


# --// Crunchbang logo //--
logo-crunch () {
    if [ -z "$L" ]; then L='\e[1;37m' ; fi
    if [ -z "$H" ]; then H='\e[1;34m' ; fi

    echo -e "
$L      888    888       888$NC
$L      888    888       888$NC\t$H $time$NC - $date
$L      888    888       888$NC\t ${USER} @ wolterBox
$L      888    888       888$NC
$L  888888888888888888   888$NC\t GTK Theme »$H $GtkTheme$NC
$L  888888888888888888   888$NC\t GTK Icons »$H $GtkIcon$NC
$L      888    888       888$NC\t GTK Font  »$H $GtkFont$NC
$L      888    888       888$NC\t Term Font »$H $TermFont$NC
$L  888888888888888888   888$NC\t Wallpaper »$H $Wallpaper$NC
$L  888888888888888888   888$NC
$L      888    888          $NC\t OS »$H $OS$NC
$L      888    888       888$NC\t WM »$H $WmVer$NC
$L      888    888       888$NC
$L      888    888       888$NC
"
    }

# --/////////////////////--
# --// Take Screenshot //--
# --/////////////////////--

take-shot () {
    # quick settings
    shotdir="$HOME/images/shots" # without the final slash
    shotname="shot_%Y-%m-%d_%H-%M-%S.png"
    quality="75" # [0-100]
    delay="5" # in seconds
    #does the shotdir exist?
    if [ ! -d "$shotdir" ]; then mkdir -p "$shotdir"; fi
    # take it!
    scrot "${shotdir}/$shotname" -q $quality -c -d $delay
}

# --//////////////////--
# --// Help Message //--
# --//////////////////--

script_name="$0"
help-message () {
echo "
USAGE: `basename $script_name` [options] [distro]

Options:
    -cn     n indicates the number of the color [0-15] of highlights
    -Cn     n indicates the number of the color [0-15] of logo
    -s      take a scheenshot (with scrot)

Available Distro (for now):
    crunch[bang]
    deb[ian]
"
}

# --///////////////////////--
# --// The Main Function //--
# --///////////////////////--

main () {
# Set the default logo (go down for available logo functions)
execute="logo-crunch"
# It will take screenshot? [0=no 1=yes]
confirm_shot="0"

    for i in "$@" ; do 
        case $i in
            -h|--help)      execute="help-message" ;;
            -c*)     cat-highlights-color $i ;;
            -C*)     cat-logo-color $i ;;
            -s)      confirm_shot="1" ;;
            deb*)    execute="logo-debian";;
            crunch*) execute="logo-crunch";;
            *)       echo -e "Unknow option ${i}\nUse the option -h for help\n\nExiting..." && exit 1;;
        esac
    done

$execute

if [ confirm_shot = "1" ] ; then
    take-shot
fi

}


# --////////////////////--
# --// EXECUTE SCRIPT //--
# --////////////////////--

main "$@"
