#!/bin/sh
#== st, tabbed

xidf="$HOME/tmp/tabbed.xid"
test -r "$xidf" && read -r -- xid <"$xidf"

if test -n "$xid" && xprop -id "$xid" 2>&1 1>/dev/null
then st -w "$((xid))" "$@" &
else tabbed -d st -w > "$xidf" && "$0" "$1"
fi
