#!/bin/zsh
#== Displays current weather info

CITY="5108093"
URL="openweathermap.org/data/2.0/weather/city/$CITY"
WGET=`wget -q $URL -O -`
data=`echo $WGET`

city=`echo "$data" | jsawk 'return this.name'`


ktemp=`echo "$data" | jsawk 'return this.main.temp'`
ctemp=`printf "%.2f" $(( ktemp - 273.15 ))`
ftemp=`printf "%.2f" $(( ctemp * 9/5 + 32 ))`

pressure=`echo $data | jsawk 'return this.main.pressure'`
humidity=`echo $data | jsawk 'return this.main.humidity'`

windSpeed=`echo $data | jsawk 'return this.wind.speed'`
cloudPerc=`echo $data | jsawk 'return this.clouds.all'`

echo "City: $city"
echo "Pressure: $pressure kPa"
echo "Temp: $ftemp° F / $ctemp° C"
echo "Humidity: $humidity%"
echo "Wind: $windSpeed m/s"